export const MSG = {
  // cat
  GET_CAT_SUCCESS: 'Lấy mặt hàng thành công',
  GET_CAT_FAILED: 'Lấy mặt hàng không thành công',
  CREATE_CAT_SUCCESS: 'Tạo mặt hàng thành công',
  CREATE_CAT_FAILED: 'Tạo mặt hàng không thành công',
  UPDATE_CAT_SUCCESS: 'Cập nhật mặt hàng thành công',
  UPDATE_CAT_FAILED: 'Cập nhật mặt hàng không thành công',

  // order
  MAKE_ORDER_FAILED: 'Tạo đơn hàng không thành công',
  MAKE_ORDER_SUCCESS: 'Tạo đơn hàng thành công',
  PLACE_ORDER_FAILED: 'Đặt hàng không thành công',
  PLACE_ORDER_SUCCESS: 'Đặt hàng thành công',
  GET_ORDER_DETAIL_FAILED: 'Tìm chi tiết đơn hàng không thành công',
  GET_ORDER_DETAIL_SUCCESS: 'Tìm chi tiết đơn hàng thành công',
  GET_PENDING_ORDER_FAILED: 'Tìm chi tiết đơn hàng không thành công',
  GET_PENDING_ORDER_SUCCESS: 'Tìm chi tiết đơn hàng thành công',
  GET_ORDER_STATUS_FAILED: 'Lấy trạng thái đơn hàng không thành công',
  GET_ORDER_STATUS_SUCCESS: 'Lấy trạng thái đơn hàng thành công',
  GET_ORDER_BY_STATUS_FAILED: 'Lọc đơn hàng theo trạng thái không thành công',
  GET_ORDER_BY_STATUS_SUCCESS: 'Lọc đơn hàng theo trạng thái thành công',
  CHANGE_ORDER_STATUS_FAILED: 'Thay đổi trạng thái đơn hàng không thành công',
  CHANGE_ORDER_STATUS_SUCCESS: 'Thay đổi trạng thái đơn hàng thành công',

  // common
  NOT_VERIFIED: 'Lỗi xác thực',
  INVALID_EMAIL: 'Email không hợp lệ',
  PLEASE_ENTER_MAIL: 'Vui lòng nhập mail và gửi lại',
  CODE_SEND_AREADY: 'Mã code đã được gửi về mail: ',
  INVALID_EMAIL_OR_PASS: 'Email hoặc mật khẩu không hợp lệ',
  SEND_OTP_FAILED: 'Mã OTP đã gửi không thành công',
  SEND_OTP_SUCCESS: 'Mã OTP đã gửi thành công',
  EMPTY_OTP: 'Mã OTP rỗng',
  VERIFY_OTP_FAILED: 'Xác thực mã OTP không thành công',
  VERIFY_OTP_SUCCESS: 'Xác thực mã OTP thành công',
  LOG_OUT_FAILED: 'Đăng xuất không thành công',
  LOG_OUT_SESSION_FAILED: 'Failed to log out session',
  LOG_OUT_SUCCESS: 'Đăng xuất thành công',
  LOG_IN_FAILED: 'Đăng nhập không thành công',
  LOG_IN_SUCCESS: 'Đăng nhập thành công',
  ADD_PRODUCT_OVER_QTY: 'Số lượng vượt quá tồn kho',
  ADD_PRODUCT_TO_CART_SUCCESS: 'Thêm vào giỏ hàng thành công',

  // customer
  CART_EMPTY_ERROR: 'Vui lòng chọn sản phẩm',
  CUSTOMER_INFO_INVALID: 'Thông tin khách hàng không hợp lệ',
  UPDATE_CUSTOMER_FAILED: 'Cập nhật thông tin khách hàng không thành công',
  UPDATE_CUSTOMER_SUCCESS: 'Cập nhật thông tin khách hàng thành công',

  // product
  GET_PRODUCT_BY_CAT_SUCCESS: 'Lọc sản phẩm theo mặt hàng thành công',
  GET_PRODUCT_BY_CAT_FAILED: 'Lọc sản phẩm theo mặt hàng không thành công',
  GET_PRODUCT_SUCCESS: 'Lấy thông tin sản phẩm thành công',
  GET_PRODUCT_FAILED: 'Lấy thông tin sản phẩm không thành công',
  GET_PRODUCT_BY_ID_SUCCESS: 'Lấy thông tin chi tiết sản phẩm thành công',
  GET_PRODUCT_BY_ID_FAILED: 'Lấy thông tin chi tiết sản phẩm không thành công',
  PRODUCT_INFO_INVALID: 'Thông tin sản phẩm không hợp lệ',
  CREATE_PRODUCT_SUCCESS: 'Tạo sản phẩm mới thành công',
  CREATE_PRODUCT_FAILED: 'Tạo sản phẩm mới không thành công',
  UPDATE_PRODUCT_SUCCESS: 'Cập nhật thông tin sản phẩm thành công',
  UPDATE_PRODUCT_FAILED: 'Cập nhật thông tin sản phẩm không thành công',
  DELETE_PRODUCT_SUCCESS: 'Xóa sản phẩm thành công',
  DELETE_PRODUCT_FAILED: 'Xóa sản phẩm không thành công',
  FIND_BY_NAME_PRODUCT_SUCCESS: 'Tìm kiếm sản phẩm thành công',
  FIND_BY_NAME_PRODUCT_FAILED: 'Tìm kiếm sản phẩm không thành công',
  ENTER_PRODUCT_SUCCESS: 'Nhập hàng thành công',
  ENTER_PRODUCT_FAILED: 'Nhập hàng không thành công',

  // user
  GET_PROFILE_SUCCESS: 'Get profile successfully',
  GET_PROFILE_FAILED: 'Failed to get profile',
  CHANGE_PASS_SUCCESS: 'Change password successfully',
  CHANGE_PASS_FAILED: 'Failed to change password',
  SEND_PASS_EMAIL: 'New password has been sent to your email',
  CREATE_USER_SUCCESS: 'Create new user successfully',
  CREATE_USER_FAILED: 'Failed to create new user',
  UPDATE_USER_SUCCESS: 'Update user successfully',
  UPDATE_USER_FAILED: 'Failed to update user',
  DELETE_USER_SUCCESS: 'Delete user successfully',
  DELETE_USER_FAILED: 'Failed to delete user',
};
